name: Main PHP Version(s) CI

on:
  push:
    branches:
      - develop
  pull_request:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-phpcs:
    name: Run PHPCS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ "8.3" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        id: ci-setup
        uses: ./.github/actions/ci-setup
        with:
          extensions: 'curl'
          extensions-cache-key: run-phpcs-${{ matrix.php-version }}
          php-version: ${{ matrix.php-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tools: 'composer, cs2pr, phpcs'

      - name: Run PHPCS
        continue-on-error: false
        id: phpcs
        run: composer phpcs
        env:
          CHANGED_FILES: ${{ steps.ci-setup.outputs.files }}
          PHP_VERSION: ${{ matrix.php-version }}

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml
